name: GUTIGON
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15608
title: GUTIGON
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#303030'
    - '#505050'
    - '#efefef'
    - '#707070'
    - '#a7a7a7'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
