name: GUTIGON
favicon: null
layout_spectrum: 0.75043
typography_spectrum: 0.10570563515648246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffce07'
    - '#5b5336'
    - '#eac017'
    - '#37311e'
  brandStrength: 0.850782977649942
  lightness: 0.3949164857622236
  saturation: 0.5104044768959284
  rhythmicContrast: 0.46262753289192915
purpose: []
