name: GUTIGON
favicon: null
layout_spectrum: 0.18454
typography_spectrum: 0.15608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffce07'
    - '#5b5336'
    - '#eac017'
    - '#37311e'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
